sudo: required

dist: xenial
language: c

branches:
  only:
    - master

services:
 - docker

matrix:
  include:
    - env:
        - VARIANT=obfuscator
        - ARCH=arm,x86
      before_install:
        - pip install --user --upgrade awscli
        - sudo apt-get update
        - sudo apt-get install -y jq
      script:
        - ./pull_ccache.bash --variant=$VARIANT --arch=$ARCH
        - VARIANT=$VARIANT ./.travis.sh
      after_success:
        - travis_wait tar -C output -cJf "llvm-$VARIANT-$ARCH.txz" .
        - ./publish.sh llvm-$VARIANT-$ARCH.txz
      after_failure:
        - ./.after_failure.sh

    - env:
        - VARIANT=vanilla
        - ARCH=arm,x86
      before_install:
        - pip install --user --upgrade awscli
        - sudo apt-get update
        - sudo apt-get install -y jq
      script:
        - ./pull_ccache.bash --variant=$VARIANT --arch=$ARCH
        - VARIANT=$VARIANT ./.travis.sh
      after_success:
        - travis_wait tar -C output -cJf "llvm-$VARIANT-$ARCH.txz" .
        - ./publish.sh llvm-$VARIANT-$ARCH.txz
      after_failure:
        - ./.after_failure.sh

env:
  global:
    - DOCKER_USER=swiftnav
    # Secure keys below are encrypted with travis encrypt gem
    # Example encryption: travis encrypt AWS_SECRET_ACCESS_KEY=foo
    # See https://docs.travis-ci.com/user/encryption-keys/
    # AWS_ACCESS_KEY_ID
    - secure: "Xwd+CuZwKCMF7zPnpE/05ZkUTfhPSft2SiWPXVEBDV2l6Ze6UQZUbjfA1/VIG/hnKTBxNP52apxH5bctHkSjF6oPgmxdOvUSwGx4kIaXYdz2gnGXfLUOJIUaXnZFNrWS66grqv0+oyv599KA8W/GoTEUARBupZN5gP0WDtCTcuBIfqUgBAjXvxMeLg2ixnZKnrCGvySsUEn6L8HVXO3XDdJKmkaBOC6G5JWdnrOL1ixyETDX8hbXCMaCOiibv1TNXOUDBrv62C7A8AnStSfSiDGzUpi/vx2HWsz2JlUBSc0bWz8PqkL7wUM/aUyGH5Er742kK9cUVLKfeiluw8krx8bLWM1W/8K7veQ3vDxyikB3SpqT/FCxDwgpQTtLUm7F4pFXRDmyhVueq3enX4oOyesYjLNwfTj0RPNOnF2sOQOyDju7VLWNoS56Tow74VaBGzxIcDnDu9deG+HDFiQtrw6tkn5B9IKS8N1ue2A1CF3QM325UjKCmBykSgomy8baaBEnNfyBFQU7L5pobvGsDoaB4dgm1YHdtYEBtFIGHEnKeAt5SzT7R6tuiABMT3SJ5Sr6n2zG7oi2bwC/CR0ch5/mZ460N76axJwLD+ORGwdCuxGII7VF4KetLFk9nkUnWRBFgU9n/m9vuN13xpAZbGblc1+WO7V1i0dnZ7uz4O4="
    # AWS_SECRET_ACCESS_KEY
    - secure: "tZ9Nmrz9hFdoc5Wdv4LBuBsfziISti2IRp8lCuU9T1uR0QZucwgL/oUdBV4MvHPj8+quD74s8h2I9XT3LhZUkxuPrZI2n++HGf+Er0gd805U+vyANszdYf12VRsTSc5WzD2SjtpbkkkWA7QxegvitBf6LwV3OjIcCqdydzbMjKTbogfOnN+HOY+3jkWsr2tyrV+JtCQbDi+C9Clc5L3X7ed38NjX0X64Pyjg8lpeI298E02wCdyF0a8osX0CrqMgK532g2C3Relrd4k4lKjf/X4mfdNbWJlPK+hv57VWrm7TuiT5fWk4SfGRMp6Y6xFuOnhWiRAYRxssS/dyd1sOXTh89YmZ/al4IrmtmRIigaZBVb7r+hRImdsT2dtRpVQ3OEVtuq1LNrx3n14Iy1JYohzGZ+8Pqolw0527uB5Y0/NzFMiDdvsM2O/MgbThgBJXfkMFhuakEYZ0VbbFQD8yLPmKY1tGxYYcMaphq6jZBLErDOAhKPeQrHkpyxuNHlujDnfFXUN4C0BwIJYCVEXyrDiW5ad0vKGJj9P6+bCt823WL4NMlUbH+YyPS8S84G2KbmaUslGYPoQOy+lfdMe/p4H9jIkzjGtvAau9cyqvWuXH/hv0zJ3NwI3iALTOdihs92KetRjuugo8rRJ+cZ3YogCffjEIwXsRs55JYSmk7HY="
    # GITHUB_TOKEN
    - secure: "T1wlLXyhfGnMNMPtHv2FspxsWG09hVZgaucSJ6IxN+PZBbgjLb/TMSlqqLXfIzx6s0SuQIzX1xZE8lb/uOzfLtjmxBdc4dGYLW+qR4AwkghQl2DGMK+hzGAi9ZbeCGKWtX7cN4WxLN1tpcTyQBCC8LcnP0xVxd+7Znytdezmlr86ce2d8dmUo+kyLdN+vhEUnch9zhMpuZI+TxV2HQqCS/6e31myP+3Xzw3B6o6uF8dYZ0QlWlNU4KjUNNAD7cLqkxNd38E7wFrQJdyrk03/hZanatl2mcL7Te5Uxo5sWN5WteTNwq8dCKXiEXpkEqP1++4wWTQDeQWoPjHlhHzO4MxGAdEUnlFWafsV78OJvr/gwV0UxDFmfadPwGG/xPPJMyNJjXwDyeztswknbVaNZdbRXp3m7Iri+bWCvOZE9N7rGde/5q0JOz9rwJXRDMPnp7+lyupHQQIdswNpkFraHz3eZ/h4n+Dkr3RtkW0M6ZpPR+/r18uD7jwm/Ye73E9wzq1b6sL0knX/OEwBv3FVvaBaA4SWzb1glDlru8BKnZfVIZ/UxYas6FqGN6H9ROyCHtva86ffv7HvvnB/gUqcOfY5si7WvtPVApIc9kfILcSWEchRWTHQIeUOdEUBfoq8/Km0BL6gguOO9Ge9zzOrdo0NThh8x7NoE0DhHdQctJY="
    # DOCKER_PASS
    - secure: "qEmUT+mBsHjLkrBYMZWiLl8+ZXq9UAv+DyMDww+N74hPtGiZxMqLuVIFq94qR/WhiI9zd7k+tjhy6TcgD8rpKoQnQSGXcotFGq6typ3UWEV0ekt40IMV5nBqopqGGIBVIHNfXjq0OTeYTF2eGncpNnznJHAQi8Dvj7vD99y5GA5RoZGSdsiqTyxBGMvZ0cE0QApkb1MH3lBVRzBuh6dotpa1RBlGR+i2xbcH3nAqy5RB38wZgMedAPnlUfg+uB+IQiF8+hbuSmHzADiabNLBkkB/UCOz59k/JkaeN+2gnyP6/so+SpOe1BKfpxKBcN74O4n056ZLDBRjTod2YSc49dKqxhZhQijwNJfFi3Tt5iNrFYdU3KPeqqfNLoQKmbBTKjGXbxHHXm3lnUuCTZH0Yd9QGKSAwn5kxDRy6DuyNMUGwFtu8YxzirwTJiQR6ayodMCMWjZCXuxUc0I5I2Y64CsofRWkuMbznjE4wJwptVPzTwIxkZnMt+aWVoQTXBtZVpiHf4CTJb65dyLDXeMOwhYnKzwLUrvvHHpOm7GygvAbbeDAzHumTDvt7s5nl2VwHNLmTK3TizvvpQCucIjG8M8dEd7iu4VRZh/rxGxV9MJ2qUNETa6hnfX+Z2xaLTcgYAG5z7p60sThPfFfYLopdJL1dO5eA/EncPzuQuh087w="
