FROM ubuntu:18.04

RUN apt-get update
RUN apt-get install -y \
    build-essential \
    clang-11 \
    clang++-11 \
    cmake \
    libc6-dev-i386 \
    python3-pip \
    python3-distutils \
    vim \
    ninja-build \
    git
