FROM ubuntu:18.04

RUN apt-get update
RUN apt-get install -y wget git

RUN \
  mkdir /opt/cmake && \
  wget -qO- https://cmake.org/files/v3.13/cmake-3.13.5-Linux-x86_64.tar.gz | \
    tar -xzf - --strip-components 1 -C /opt/cmake

ENV PATH=/opt/cmake/bin:${PATH}
