---
name: aarch64 sysroot
on:
  pull_request:
    paths:
      - "aarch64-sysroot/**"
      - .github/workflows/aarch64-sysroot.yaml
  push:
    tags:
      - "aarch64-sysroot-*"

jobs:
  toolchains:
    runs-on: ubuntu-22.04
    name: aarch64 sysroot
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Create sysroot
        run: ./aarch64-sysroot/sysroot-creator.sh build arm64

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: aarch64-sysroot/out/sysroot-build/bullseye/debian_bullseye_arm64_sysroot.tar.xz

      - name: Upload sysroot
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "aarch64-sysroot/out/sysroot-build/bullseye/debian_bullseye_arm64_sysroot.tar.xz"
          tag: ${{ github.ref }}
          overwrite: true
